### ISSUE TITLE
There should be a workflow to change the AbID prefix for an existing AbID when it changes size

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/abid#144]
![image](https://github.com/pulibrary/abid/assets/2806645/d65420e9-176b-4196-956f-0295bdc8c74f)

For a MARC item a piece changed size and needed a new AbID (because it was getting moved to another place) - there should be a way to force this through.

NOTE we discovered today: Sometimes they'll have changed the barcode in Alma because there's a new barcode but not a new holding ID. So you can't search for the old barcode and change that AbID, you'll have to delete whatever AbID the validator returns. Maybe show them which barcode they'd be deleting. When they change the enclosure of the item they might change the barcode.

## Sudden Priority Justification

Closing this ticket will prevent future sudden priorities when Michael's unable to do his job because of this feature on a project that's in maintenance status.

**Comment by tpendragon** [comment]
The old system had a pop-up that asked if you "do want to replace the AbID"

**Comment by tpendragon** [comment]
I've deleted that AbID from the system like this, to unblock Michael:

```ruby
item = Alma::BibItem.find_by_barcode("32101113873150")
holding_id = item["holding_data"]["holding_id"]
abid = AbsoluteIdentifier.where(holding_id: holding_id)
abid.last.destroy
```

**Comment by hackartisan** [comment]
Discussion:

workflow for Marc AbID
- An abid is an absolute identifier, that designates a spot on the shelf. E.g. if it’s Q01 it’s the first thing in the Q section.
- They bring 30 books to the office that have already been cataloged in Alma and they already have barcodes in them.
- They say “it’s folio”
- they scan all 36 in order.
- the app generates an AbID for each of them. They are sequential.
- Synchronizing means it gets put in a field in the Alma record.
- New use case: I had a folder. someone pulled it out and put it in a box. Now it’s not a folder anymore. It has the same barcode because it’s the same item.
- Need a button that lets you set a new prefix
- the default interface is aspace, and there’s also a button for Marc batches.
  - this feature is behind the “marc batches” button.
- Question: Is abid-staging hooked to staging instances of aspace and alma?
  - probably, but not entirely sure.
