### ISSUE TITLE
AbID for MARC with Alma

### ISSUE THREAD

**Issue by kelynch** [pulibrary/abid#42]
Use Case:

- I'm sent a bunch of rare books which are stacked up on my desk and sorted by size. I need to generate AbIDs for them and then get those AbIDs into Alma.

Post-June MVP: From a list of barcodes and associated sizes provided by CaMS, look up Alma holdings IDs, associate them with their sizes, and then create one new AbID per holding record.  

Some rules:
* If CaMS provides more than 1 size per holdings record , log and skip
* If the barcode is not in Alma, log and skip

Add the abID value to the holdings 852 subfield h in a MARC record in Alma, using the Alma API. Set 852 first indicator to 8.

Some rules:
* If the record has no 852h field, add one with the abID.
* If the record has an existing 852h field, overwrite it with the new abID value.
* If the record has more than one 852h field, log and skip this one, as this indicates a problem with the source record.

Export a text file of processed barcodes that have been processed, to be used by CaMS with the SpineOMatic.  Report all logged and skipped barcodes to CaMS.

For reference - https://docs.google.com/document/d/1yZs_AAmwWtrfQFAtCVj7XfF9V_LYEBSicI6yU23vfuY/edit#heading=h.mhn7ij3ez0kk 

## Note

We're blocking this ticket until we have the alma sandbox so we can safely test edits.

**Comment by doncat** [comment]
Perfectly stated!  If this can be created it will be vastly simpler than what we do now in Voyager.

**Comment by tpendragon** [comment]
@doncat Why does CAMs want to submit a text file rather than just filling out the form with two fields, First Barcode, Size, Count or something? Do you tend to not process multiple concurrent boxes?

**Comment by doncat** [comment]
I described the process for MARC item-level cataloging.  The header of this ticket is wrong; ASpace has nothing to do with it.  
The text file shows what the operator knows: a bunch of volumes, etc., each with its own barcode already assigned.  Each one is in a size category.  
The lib-jobs form would be a dreadful imposition for the one-at-a-time process that applies to MARC.  That's why the original database has a "metadata format" option.  It's two different paths.

**Comment by tpendragon** [comment]
I see, so they're not attaching barcodes from a reel, the books already have barcodes because they've been catalogued.

**Comment by tpendragon** [comment]
@doncat This is rare books so I realize it's unlikely, but there's no case where I have two items of the same holding? Would the goal there be that both barcodes get the same AbID?

**Comment by doncat** [comment]
To start with, "rare books" is a meaningless phrase.  SC collections aren't different from anything else.  (I have statistical demonstration of this fact!)
Yes, it's entirely possible to have two items for the same holding.  Such a case is included in the sample records in the related document. 
Oh, and can someone add "Set 852 1st indicator to '8'" in the preceding?  I forgot that change.  "8" means local.

**Comment by hackartisan** [comment]
Blocked until we get the premium sandbox Aug 11

**Comment by tpendragon** [comment]
@doncat I'm looking at this now. Do you have an example of a record that has an 852h already, so I can compare the data that comes out of alma with one that doesn't?

**Comment by doncat** [comment]
Anything with 852h beginning “item” followed by digits. That’s what we’ve used for in-process items. To be replaced by the new AbID.
Don
________________________________

**Comment by tpendragon** [comment]
@doncat I don't really have a way to search for that. Can you or someone else provide me an MMSID or holding ID for a record that has this 852h?

Thank you!

**Comment by doncat** [comment]
9932213323506421 or 9932049173506421.
99102626323506421, holding 22506548920006421.

**Comment by tpendragon** [comment]
@doncat You're the best, thanks for taking the time finding that for me.

**Comment by tpendragon** [comment]
@doncat If given two items with two barcodes that are under the same holding and the same size category, should only one AbID be added as aan 852, or should a second 852 be generated? If only one, then which one? The first one or the second one?

**Comment by doncat** [comment]
Only one AbID, per MARC structure.  You're looking for distinct values of holdings records, as in the last two examples.
Already an AbID:  Hmm.  That might represent a workflow detour!  Uh, hmm.  Uh.  I don't think it's supposed to happen because the cataloger knows the item is an added volume.  But nonetheless, if you detect an existing AbID, don't generate a new one but do include the barcode in the file you return to us.  We need it for label printing (if we can get SpineOMatic configured).
Does "detect" an existing AbID make sense?  I'm now asking you to check for a pattern in 852h, instead of just identifying the holdings record.
